"""add unique student internship

Revision ID: af6ade1c5946
Revises: 92a9df428e9f
Create Date: 2026-10-08 23:56:47.381497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6ade1c5946'
down_revision: Union[str, Sequence[str], None] = '92a9df428e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint( "unique_student_internship",'student_internship', ['student_id', 'internship_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(
        "unique_student_internship",
        "student_internship",
        type_="unique"
    )